### PR TITLE
Update README.md with BarGraph usage examples

### PR DESCRIPTION
**Pull request by boronhub**
Also added structure to include usage examples for all graph types

### CODE REVIEW

**Comment by WilliamHYZhang** [comment]
@boronhub do you mind making a separate branch in your fork for your two pulls? Thanks!

In order not to clog up the README, maybe instead we can just direct users to the testing folder where they can browse code examples and output of all of the graphs?

**Comment by KarthikRIyer** [comment]
I agree with @WilliamHYZhang. You should have a separate branch for each PR that you work on.

Also, because we have a dedicated Tests/examples directory included with the repository we shouldn't need to have examples for everything in the README. Instead of having these extra examples, you could just add something like this:

For examples of other plot types and features refer to the [Tests](https://github.com/KarthikRIyer/swiftplot/tree/master/Tests/SwiftPlotTests) directory.

**Comment by boronhub** [comment]
Apologies for the branch thing, I created a new one but I guess I forgot to push that one.

And yes, I also had the feeling the README would be too dense, so I wanted to know what @KarthikRIyer thought of maybe reducing the number of LineGraph examples, and have maybe one/two usage examples per graph type (most common uses) .

**Comment by WilliamHYZhang** [comment]
+1 on @KarthikRIyer's suggestion.

**Comment by KarthikRIyer** [comment]
@boronhub I'd like to keep the current examples because they demonstrate some of the basic features of the framework, the usage of which will be similar in other plots. Take sub plots for example. The method to create sub plots will remain the same everywhere. If you want to add more series to bar graph the syntax remains almost same.

**Comment by KarthikRIyer** [comment]
@boronhub would you like to add the link to the tests directory to the README?

**Pull request closed without merging**
