### PR TITLE
Center image in README

### PR DESCRIPTION
**Pull request by rickwierenga**

### CODE REVIEW

**Comment by KarthikRIyer** [comment]
I don't think this makes a very significant difference. While creating the docs I preferred the left alignment.

**Comment by rickwierenga** [comment]
That's OK—it's your library. Feel free to close this PR.

**Comment by KarthikRIyer** [comment]
I don't have a very strong preference regarding this. If others feel this is a better option I'd be happy to incorporate it. So I'll leave it open for now. 
Thank you for the PR 😄

**Comment by rickwierenga** [comment]
It was just a thing that came to my mind.

I hope to make a more meaningful contribution to this project through GCI later this month :D

**Comment by KarthikRIyer** [comment]
@rickwierenga that's great. Looking forward to working with you on this! :)

**Pull request closed without merging**
