### PR TITLE
bfix: Use color alpha while drawing text in SVG Renderer

### PR DESCRIPTION
**Pull request by KarthikRIyer**
We weren't using the alpha of the color while drawing text in svg renderer. I've fixed that here. Noticed it in the watermark example added by @WilliamHYZhang recently.

### CODE REVIEW

**Comment by KarthikRIyer** [comment]
@karwa @odmir how is it that `testHistogramStackedStepOffset()` this test runs on macOS without being mentioned in the manifest, but not on Linux. This seems to be the reason test is failing.

**Comment by odmir** [comment]
On macOS it never uses the manifest I think and just uses the Objective-C runtime to discover the tests. The same behaviour should be possible now on Linux with the `--enable-test-discovery` flag though, although only on the latest swift snapshots.

One thing is that there might be a bug in the current implementation which we would run into:
https://bugs.swift.org/browse/SR-11951

**Comment by karwa** [comment]
Yup, macOS uses the Obj-C runtime to discover tests. It’s annoying, but test discovery apparently isn’t on by default on Linux (yet)

**Comment by KarthikRIyer** [comment]
I'm running into the bug @odmir mentioned above. If I merge this PR could either @karwa or @odmir add the test image in another PR?

**Comment by odmir** [comment]
Sure, go ahead!

**Comment by KarthikRIyer** [comment]
@odmir done.

**Pull request merged**
