### PR TITLE
Add Anchor Support for Annotations

### PR DESCRIPTION
**Pull request by WilliamHYZhang**
Introducing the newest feature for annotations, the ability to anchor them to anything! This idea started as just to anchor text annotations, but with the help of some nifty tricks we can expand this significantly. Here's an overview of what I did in this PR:

- Implement new `enum`, `Direction`. This is where we specify the north/east/south/west direction that we would like to anchor to.
- Implement new protocol, `Anchor`. This extends `Annotation` to include a direction and a float buffer (space desired between the annotation and the anchor point). We also require a `resolve` function that will deal with the anchor directions and update the parameters of the annotation accordingly.
- Have our existing `Box` and `Text` annotations also conform to `Anchor`. Now, we could just replace this with just conforming to `Anchor` as it extends `Annotation`, however I think that this definition is more verbose.
- Update the `Arrow` annotation to support anchoring of any annotation that supports it. Also included an option to override the anchor and force to draw at passed coordinates if the user desires.
- Update the arrow tests to support this feature- no more "guess and check" to find the locations to pass anymore!

So what does this mean for the future of annotations in SwiftPlot?

- Adding annotations will be pretty straightforward. If we don't want it to support anchoring, that's fine. Otherwise, conform it to `Anchor` and we're good to go.
- This introduces the possibility to anchor the annotations to anything we want, not just the ends of an arrow. We can pass any point we'd like to the `resolve` function and it will relocate itself. We can make it anchored to the origin, ends of lines in line graphs, etc... the list is endless.

Anyways, hope you guys like it. I'm definitely open to any suggestions for improvements or new ideas. Feel free to check it out.

William

### CODE REVIEW

**Comment by WilliamHYZhang** [comment]
Oooof. PR build is failing... I'll look into it.

**Comment by WilliamHYZhang** [comment]
Fixed, @karwa when this is merged may you rerun quartz tests when you have time? No hurry.

**Comment by WilliamHYZhang** [comment]
@KarthikRIyer resolved merge conflicts

**Comment by KarthikRIyer** [comment]
Great work @WilliamHYZhang. I really like how you've approached the problem! I have some suggestions:
- Instead of `Anchor`, I think `AnchorableAnnotation` makes more sense.
- Instead of buffer, does margin seem more suitable, because when I first read Float buffer, I thought about a Float array and was wondering how that was required.
- In the example It would be nice if the text is anchored at the middle of it's height.

**Review by KarthikRIyer — COMMENTED** [review]
Great work @WilliamHYZhang. I really like how you've approached the problem! I have some suggestions:

- Instead of Anchor, I think AnchorableAnnotation makes more sense.
- Instead of buffer, does margin seem more suitable, because when I first read Float buffer, I thought about a Float array and was wondering how that was required.
- In the example It would be nice if the text is anchored at the middle of it's height.

**Comment by WilliamHYZhang** [comment]
@KarthikRIyer should be good to go.

**Comment by KarthikRIyer** [comment]
Looks good @WilliamHYZhang. Good job!

**Pull request merged**
